### ISSUE TITLE
Unable to craft

### ISSUE THREAD

**Issue by Nimflora** [ToroCraft/TorchArrows#2]
Not only does the item name appear oddly (item.torcharrow or something) but I'm unable to craft the arrows. Coal+stick+feather yields no product in the crafting table.

**Comment by frodare** [comment]
What forge version and Torch Arrow version are you using?

**Comment by Nimflora** [comment]
Forge1.12-14.21.1.2404 , and I tried with both torcharrows-1.12 AND torcharrows-1.12-2

**Comment by Nimflora** [comment]
???

**Comment by frodare** [comment]
Thanks for posting this issue. I probably will not get around to fixing this for at least a few more days.  These types of issues will happen while 1.12 is stabilizing.

**Comment by zeriley** [comment]
Fixed in 1.12-3
